import { Stack, Slider } from '@mui/material'
import PropTypes from 'prop-types'
import * as R from 'ramda'
import { useCallback, useMemo, useState, useEffect, useRef } from 'react'
import { useSelector } from 'react-redux'

import { selectNumberFormatPropsFn } from '../../data/selectors'
import { getInverseScaleTransform, getScaleTransform } from '../../utils/scales'
import NumberField from '../prototypes/NumberField'

import { forceArray, NumberFormat } from '../../utils'

const styles = {
  root: { alignItems: 'center' },
  getSlider: (color) => ({
    mx: '27px',
    mb: 1,
    py: 1.5,
    '& .MuiSlider-rail': {
      height: '4px',
      borderRadius: 1,
      bgcolor: color,
    },
    '& .MuiSlider-thumb': {
      height: '24px',
      width: '24px',
      bgcolor: color,
    },
    '& .MuiSlider-track': {
      height: '4px',
      borderRadius: 1,
    },
  }),
}

const PropNumberSlider = ({ prop, currentVal, sx = [], onChange }) => {
  const {
    enabled,
    slotProps,
    fullWidth = true,
    scale,
    scaleParams,
    hideKeyboardToggle,
    color,
    propStyle,
  } = prop

  const scaleFunc = useMemo(
    () => getScaleTransform(scale, scaleParams),
    [scale, scaleParams]
  )

  const invScaleFunc = useMemo(
    () => getInverseScaleTransform(scale, scaleParams),
    [scale, scaleParams]
  )

  const [value, setValue] = useState(invScaleFunc(currentVal ?? prop.value))
  const lastSentRef = useRef(currentVal ?? prop.value)

  useEffect(() => {
    const rawVal = currentVal ?? prop.value
    setValue(invScaleFunc(rawVal))
    lastSentRef.current = rawVal
  }, [currentVal, invScaleFunc, prop.value])

  // Here, units are excluded from `format` as
  // they are rendered in the prop container
  // eslint-disable-next-line no-unused-vars
  const { unit, unitPlacement, ...numberFormatProps } = useSelector(
    selectNumberFormatPropsFn
  )(prop)

  const minValue = prop.minValue ?? -Infinity
  const rawMaxValue = prop.maxValue ?? Infinity
  const maxValue = minValue === rawMaxValue ? minValue + 1 : rawMaxValue

  const scaledMinValue = invScaleFunc(minValue)
  const scaledMaxValue = invScaleFunc(maxValue)

  const getLabelFormat = useCallback(
    (sliderValue) =>
      NumberFormat.format(sliderValue, {
        ...numberFormatProps,
        trailingZeros: false,
      }),
    [numberFormatProps]
  )

  const marks = useMemo(
    () => [
      { value: scaledMinValue, label: getLabelFormat(minValue) },
      { value: scaledMaxValue, label: getLabelFormat(maxValue) },
    ],
    [getLabelFormat, minValue, maxValue, scaledMinValue, scaledMaxValue]
  )

  const handleChange = (event, newValue) => {
    setValue(newValue)
  }

  const handleChangeCommitted = (event, newValue) => {
    if (
      !enabled ||
      // ignore mouseup events generated by touch events
      (event?.type === 'mouseup' &&
        R.pathOr(false, ['sourceCapabilities', 'firesTouchEvents'], event))
    )
      return
    const scaled = scaleFunc(newValue)
    if (scaled === lastSentRef.current) return
    lastSentRef.current = scaled
    onChange(scaled)
  }

  const step = useMemo(
    () => 1 / 10 ** (numberFormatProps.precision ?? 2),
    [numberFormatProps.precision]
  )

  return (
    <Stack
      useFlexGap
      direction="row"
      spacing={1}
      sx={[
        styles.root,
        ...forceArray(sx),
        fullWidth && { width: '100%' },
        ...forceArray(propStyle),
      ]}
    >
      <Slider
        disabled={!enabled}
        min={scaledMinValue}
        max={scaledMaxValue}
        track={false}
        scale={scaleFunc}
        valueLabelDisplay="auto"
        valueLabelFormat={getLabelFormat}
        {...{ marks, step, value, ...slotProps?.slider }}
        sx={[styles.getSlider(color), ...forceArray(slotProps?.slider?.sx)]}
        onChange={handleChange}
        onChangeCommitted={handleChangeCommitted}
      />

      <NumberField
        disabled={!enabled}
        slotProps={{
          ...slotProps,
          input: {
            ...slotProps?.input,
            sx: [{ textAlign: 'center' }, ...forceArray(slotProps?.input?.sx)],
          },
        }}
        sx={{ maxWidth: '50%' }}
        min={scaledMinValue}
        max={scaledMaxValue}
        scale={scaleFunc}
        inverseScale={invScaleFunc}
        {...{ value, step, hideKeyboardToggle }}
        spinner="leftAndRight"
        size="small"
        numberFormat={numberFormatProps}
        onChange={handleChange}
        onChangeCommitted={handleChangeCommitted}
      />
    </Stack>
  )
}
PropNumberSlider.propTypes = {
  prop: PropTypes.object,
  currentVal: PropTypes.number,
  sx: PropTypes.oneOfType([
    PropTypes.arrayOf(
      PropTypes.oneOfType([PropTypes.func, PropTypes.object, PropTypes.bool])
    ),
    PropTypes.func,
    PropTypes.object,
  ]),
  onChange: PropTypes.func,
}

export default PropNumberSlider
