import { Stack, Slider } from '@mui/material'
import PropTypes from 'prop-types'
import * as R from 'ramda'
import { useCallback, useMemo, useState } from 'react'
import { useSelector } from 'react-redux'

import { selectNumberFormatPropsFn } from '../../data/selectors'
import NumberField from '../prototypes/NumberField'

import { forceArray, getSliderMarks, NumberFormat } from '../../utils'

const styles = {
  root: { alignItems: 'center' },
  getSlider: (color) => ({
    mx: '27px',
    mb: 1,
    py: 1.5,
    '& .MuiSlider-rail': {
      height: '4px',
      borderRadius: 1,
      bgcolor: color,
    },
    '& .MuiSlider-thumb': {
      height: '24px',
      width: '24px',
      bgcolor: color,
    },
    '& .MuiSlider-track': {
      height: '4px',
      borderRadius: 1,
    },
  }),
}

const PropNumberSlider = ({ prop, currentVal, sx = [], onChange }) => {
  const [value, setValue] = useState(currentVal ?? prop.value)
  // Here, units are excluded from `format` as
  // they are rendered in the prop container
  // eslint-disable-next-line no-unused-vars
  const { unit, unitPlacement, ...numberFormatProps } = useSelector(
    selectNumberFormatPropsFn
  )(prop)

  const { enabled, slotProps = {}, fullWidth = true, color, propStyle } = prop

  const minValue = prop.minValue ?? -Infinity
  const maxValue = useMemo(() => {
    const rawMaxValue = prop.maxValue ?? Infinity
    return minValue === rawMaxValue ? minValue + 1 : rawMaxValue
  }, [minValue, prop.maxValue])

  const getLabelFormat = useCallback(
    (sliderValue) =>
      NumberFormat.format(sliderValue, {
        ...numberFormatProps,
        trailingZeros: false,
      }),
    [numberFormatProps]
  )

  const marks = useMemo(
    () => getSliderMarks(minValue, maxValue, 2, getLabelFormat),
    [getLabelFormat, maxValue, minValue]
  )

  const handleChange = (event, newValue) => {
    setValue(newValue)
  }

  const handleChangeCommitted = useCallback(
    (event, newValue) => {
      if (
        !enabled ||
        // ignore mouseup events generated by touch events}
        (event.type === 'mouseup' &&
          R.pathOr(false, ['sourceCapabilities', 'firesTouchEvents'], event))
      )
        return
      onChange(newValue)
    },
    [enabled, onChange]
  )

  const step = useMemo(
    () => 1 / Math.pow(10, numberFormatProps.precision ?? 2),
    [numberFormatProps.precision]
  )

  return (
    <Stack
      useFlexGap
      direction="row"
      spacing={1}
      sx={[
        styles.root,
        ...forceArray(sx),
        fullWidth && { width: '100%' },
        ...forceArray(propStyle),
      ]}
    >
      <Slider
        disabled={!enabled}
        min={minValue}
        max={maxValue}
        track={false}
        valueLabelDisplay="auto"
        valueLabelFormat={getLabelFormat}
        {...{ marks, step, value, ...slotProps.slider }}
        sx={[styles.getSlider(color), ...forceArray(slotProps.slider?.sx)]}
        onChange={handleChange}
        onChangeCommitted={handleChangeCommitted}
      />

      <NumberField
        disabled={!enabled}
        slotProps={{
          ...slotProps,
          input: {
            ...slotProps.input,
            sx: [{ textAlign: 'center' }, ...forceArray(slotProps?.input?.sx)],
          },
        }}
        sx={{ maxWidth: '50%' }}
        min={minValue}
        max={maxValue}
        {...{ value }}
        spinner="leftAndRight"
        size="small"
        numberFormat={numberFormatProps}
        onChange={handleChange}
        onChangeCommitted={handleChangeCommitted}
      />
    </Stack>
  )
}
PropNumberSlider.propTypes = {
  prop: PropTypes.object,
  currentVal: PropTypes.number,
  onChange: PropTypes.func,
}

export default PropNumberSlider
